using UnityEngine;
using UnityEngine.SceneManagement;

public class LaunchPlayer : MonoBehaviour
{

    [SerializeField] int power = 1000;
    [SerializeField] GameObject RestartButton;
    [SerializeField] GameObject EndButton;
    public string groundTag = "Ground"; // ï¿½nï¿½Ê‚Ìƒ^ï¿½O
    public float stopThreshold = 0.1f; // ï¿½ï¿½ï¿½xè‡’l
    private bool isLanded = false;

    LoadValue loadValue;
    Rigidbody rb;


    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        loadValue = this.GetComponent<LoadValue>();
        rb = this.GetComponent<Rigidbody>();

        RestartButton.SetActive(false);
        EndButton.SetActive(false);
    }

    // Update is called once per frame
    void Update()
    {
        if (loadValue.decideAngle)
        {
            rb.useGravity = true;
            rb.AddForce(this.transform.up * loadValue.shakeCount * power);
            loadValue.decideAngle = false;
        }
    }

    void FixedUpdate()
    {
        if (isLanded)
        {
            float speed = rb.linearVelocity.magnitude;
            if (speed < stopThreshold || rb.IsSleeping())
            {
                RestartButton.SetActive(true);
                EndButton.SetActive(true);


                Debug.Log("ï¿½ï¿½ï¿½Sï¿½ÉŽ~ï¿½Ü‚ï¿½Ü‚ï¿½ï¿½ï¿½");
                // ï¿½ï¿½ï¿½ï¿½ï¿½ÅŽ~ï¿½Ü‚èˆï¿½ï¿½ï¿½iï¿½ï¿½: ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ÏXï¿½j
            }
        }
    }

    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag(groundTag))
        {
            // ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½m: ï¿½ï¿½ï¿½ï¿½ï¿½Å’ï¿½ï¿½nï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½ð”­‰ï¿½
            RestartButton.SetActive(true);
            EndButton.SetActive(true);
            Debug.Log("ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½");
            // ï¿½~ï¿½Ü‚ï¿½mï¿½Fï¿½ÖˆÚs
        }
    }

    public void RestartScene()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }


        public void QuitGame()
        {
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
        }
}
